/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schliessfach.dialoge;


import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.jdesktop.application.ResourceMap;

import schliessfach.Schliessfach;
import schliessfach.Schluessel;
import schliessfach.SchliessfachApp;

/**
 *
 * @author fschuett
 */
public class SchluesselDlg extends javax.swing.JDialog {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Schliessfach sf;
    private ResourceMap resourceMap;
    
    /**
     * Creates new form SchluesselDlg
     * @param parent
     * @param modal
     * @param sf
     */
    public SchluesselDlg(java.awt.Frame parent, boolean modal, Schliessfach sf) {
        super(parent, modal);
        this.sf = sf;
        initComponents();
    }

    /**
     * @wbp.parser.constructor
     */
    public SchluesselDlg(java.awt.Frame parent, boolean modal) {
    	this(parent, modal, null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        em = SchliessfachApp.getApplication().em;
        schluesselQuery = java.beans.Beans.isDesignTime() ? null : em.createQuery(org.jdesktop.application.Application
            .getInstance(schliessfach.SchliessfachApp.class)
            .getContext()
            .getResourceMap(SchluesselDlg.class)
            .getString("schluesselQuery.query"))
        .setParameter("sf", sf);
        schluesselListe = java.beans.Beans.isDesignTime() ? java.util.Collections
        .emptyList()
        : org.jdesktop.observablecollections.ObservableCollections
        .observableList(new java.util.LinkedList(
            schluesselQuery.getResultList()));
    schliessfachPanel = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    schluesselTabelle = new javax.swing.JTable();
    buttonPanel = new javax.swing.JPanel();
    add = new javax.swing.JButton();
    schliessen = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    schliessfachPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Schlüsselliste", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(52, 7, 211))); // NOI18N

    schluesselTabelle.setColumnSelectionAllowed(false);
    schluesselTabelle.getTableHeader().setReorderingAllowed(false);

    org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, schluesselListe, schluesselTabelle);
    org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nr}"));
    columnBinding.setColumnName("Nr");
    columnBinding.setColumnClass(Long.class);
    columnBinding.setEditable(false);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${schliessfach.nr}"));
    columnBinding.setColumnName("Fach");
    columnBinding.setColumnClass(Long.class);
    columnBinding.setEditable(false);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ausgegeben}"));
    columnBinding.setColumnName("Ausgegeben");
    columnBinding.setColumnClass(Boolean.class);
    columnBinding.setEditable(false);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${anVertrag.id}"));
    columnBinding.setColumnName("Vertrag");
    columnBinding.setColumnClass(Long.class);
    columnBinding.setEditable(false);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${kommentar}"));
    columnBinding.setColumnName("Kommentar");
    columnBinding.setColumnClass(String.class);
    columnBinding.setEditable(false);
    bindingGroup.addBinding(jTableBinding);
    jTableBinding.bind();
    jScrollPane1.setViewportView(schluesselTabelle);
    schluesselTabelle.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

    buttonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Schlüssel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(24, 8, 241))); // NOI18N
    buttonPanel.setLayout(new java.awt.GridLayout(1, 1, 10, 0));

    add.setText("Hinzufügen");
    add.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            addActionPerformed(evt);
        }
    });
    buttonPanel.add(add);

    javax.swing.GroupLayout schliessfachPanelLayout = new javax.swing.GroupLayout(schliessfachPanel);
    schliessfachPanel.setLayout(schliessfachPanelLayout);
    schliessfachPanelLayout.setHorizontalGroup(
        schliessfachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, schliessfachPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    schliessfachPanelLayout.setVerticalGroup(
        schliessfachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(schliessfachPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(schliessfachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGroup(schliessfachPanelLayout.createSequentialGroup()
                    .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 55, Short.MAX_VALUE)))
            .addContainerGap())
    );

    schliessen.setText("Schließen");
    schliessen.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            schliessenActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(schliessfachPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(schliessen)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(schliessfachPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addComponent(schliessen)
            .addContainerGap())
    );

    bindingGroup.bind();

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        Schluessel s = new Schluessel();
        s.setSchliessfach(sf);
        s.setNr(findeFreieSchluesselNummer(schluesselListe));
        em.getTransaction().begin();
        em.persist(s);
        em.getTransaction().commit();
        aktualisiereSchluesselListe();
    }//GEN-LAST:event_addActionPerformed

    private long findeFreieSchluesselNummer(List<Schluessel> liste){
    	Set<Long> used = new HashSet<Long>();
    	for(Schluessel sl : liste)
    		used.add(sl.getNr());
    	long ret = 1;
    	while(used.contains(ret))
    		ret++;
    	return ret;
    }
    
    private void schliessenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schliessenActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_schliessenActionPerformed

    private void aktualisiereSchluesselListe() {
        if (schluesselListe != null) {
            schluesselListe.clear();
            if (sf != null && schluesselQuery != null) {
                schluesselQuery.setParameter("sf", sf);
                schluesselListe.addAll(schluesselQuery.getResultList());
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchluesselDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchluesselDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchluesselDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchluesselDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SchluesselDlg dialog = new SchluesselDlg(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JPanel buttonPanel;
    private javax.persistence.EntityManager em;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton schliessen;
    private javax.swing.JPanel schliessfachPanel;
    private java.util.List schluesselListe;
    private javax.persistence.Query schluesselQuery;
    private javax.swing.JTable schluesselTabelle;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
