/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SchliessfachschrankPanel.java
 *
 * Created on 14.09.2011, 12:17:17
 */

package schliessfach.dialoge;

import java.util.Iterator;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.border.TitledBorder;
import schliessfach.Schliessfach;
import schliessfach.SchliessfachApp;
import schliessfach.Schliessfachschrank;

/**
 *
 * @author fschuett
 */
public class SchliessfachschrankPanel extends javax.swing.JPanel {
    private EntityManager em;
    private Schliessfachschrank schrank;
    private javax.swing.JToggleButton[] fach;
    private static final int ANZAHL = 12;
    /** Creates new form SchliessfachschrankPanel */
    public SchliessfachschrankPanel(Schliessfachschrank schrank) {
        this.em = SchliessfachApp.getApplication().em;
        this.fach = new javax.swing.JToggleButton[ANZAHL];
        this.schrank = schrank;
        initComponents();
        setzeStandort();
        setzeSchrankNummern();
        schliesseVergebeneFaecher();
    }

    public void setGewaehltesFach(Long nr){
        if(schrank == null || nr < schrank.getErsteNummer() || nr > schrank.getLetzteNummer())
            return;
        nr -= schrank.getErsteNummer();
        if(fach[nr.intValue()].isEnabled())
            auswahl.setSelected(fach[nr.intValue()].getModel(), true);
    }

    public Long getGewaehltesFach(){
        if(schrank == null || auswahl.getSelection() == null)
            return -1L;
        else
            for(int i=0;i<ANZAHL;i++)
                if(auswahl.isSelected(fach[i].getModel()))
                    return schrank.getErsteNummer()+i;
        return -1L;
    }

    private void setzeStandort(){
        String standOrt;
        if(schrank == null)
            standOrt = "";
        else
            standOrt = schrank.getOrt();
        ((TitledBorder)this.getBorder()).setTitle(standOrt);
    }
    
    private void setzeSchrankNummern(){
        for(int i=0;i<ANZAHL;i++){
            if(schrank == null)
                fach[i].setText("");
            else
                fach[i].setText(Long.toString(schrank.getErsteNummer()+i));
            fach[i].setToolTipText("");
        }
    }

    public void setSchrank(Schliessfachschrank schrank){
        this.schrank = schrank;
        setzeStandort();
        setzeSchrankNummern();
        schliesseVergebeneFaecher();
    }

    public Schliessfachschrank getSchrank(){
        return schrank;
    }

    private void schliesseVergebeneFaecher(){
        for(int i=0;i<ANZAHL;i++){
            fach[i].setSelected(false);
            fach[i].setEnabled(true);
            auswahl.add(fach[i]);
        }
        if(schrank == null)
            return;
        Query q = em.createQuery("SELECT s.nr FROM Vertrag v JOIN v.schliessfach s WHERE s.nr BETWEEN :ersteNummer AND :letzteNummer");
        q.setParameter("ersteNummer", schrank.getErsteNummer());
        q.setParameter("letzteNummer", schrank.getLetzteNummer());
        Iterator<Long> it = q.getResultList().listIterator();
        while(it.hasNext()){
            int nr = (int) (it.next() - schrank.getErsteNummer());
            fach[nr].setSelected(true);
            fach[nr].setEnabled(false);
            auswahl.remove(fach[nr]);
        }
        q = em.createQuery("SELECT s FROM Schliessfach s WHERE s.nr BETWEEN :ersteNummer AND :letzteNummer AND NOT s.kommentar IS NULL");
        q.setParameter("ersteNummer", schrank.getErsteNummer());
        q.setParameter("letzteNummer", schrank.getLetzteNummer());
        Iterator<Schliessfach> its = q.getResultList().listIterator();
        while(its.hasNext()){
            Schliessfach s = (Schliessfach) its.next();
            int nr = (int) (s.getNr() - schrank.getErsteNummer());
            fach[nr].setSelected(true);
            fach[nr].setEnabled(false);
            fach[nr].setToolTipText(s.getKommentar());
            fach[nr].setText(fach[nr].getText()+"\nxxx");
            auswahl.remove(fach[nr]);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        auswahl = new javax.swing.ButtonGroup();
        fach0 = new javax.swing.JToggleButton();
        fach[0] = fach0;
        fach4 = new javax.swing.JToggleButton();
        fach[4] = fach4;
        fach8 = new javax.swing.JToggleButton();
        fach[8] = fach8;
        fach1 = new javax.swing.JToggleButton();
        fach[1] = fach1;
        fach5 = new javax.swing.JToggleButton();
        fach[5] = fach5;
        fach9 = new javax.swing.JToggleButton();
        fach[9] = fach9;
        fach2 = new javax.swing.JToggleButton();
        fach[2] = fach2;
        fach6 = new javax.swing.JToggleButton();
        fach[6] = fach6;
        fach10 = new javax.swing.JToggleButton();
        fach[10] = fach10;
        fach3 = new javax.swing.JToggleButton();
        fach[3] = fach3;
        fach7 = new javax.swing.JToggleButton();
        fach[7] = fach7;
        fach11 = new javax.swing.JToggleButton();
        fach[11] = fach11;

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, schrank == null ? " " : schrank.getOrt(), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        setMaximumSize(new java.awt.Dimension(454, 288));
        setMinimumSize(new java.awt.Dimension(454, 288));
        setPreferredSize(new java.awt.Dimension(454, 288));
        setLayout(new java.awt.GridLayout(4, 3, 10, 10));

        fach0.setBackground(new java.awt.Color(248, 251, 73));
        fach0.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fach0.setText("0");
        fach0.setMaximumSize(new java.awt.Dimension(32000, 32000));
        fach0.setMinimumSize(new java.awt.Dimension(20, 10));
        fach0.setName("fach0"); // NOI18N
        add(fach0);

        fach4.setBackground(new java.awt.Color(107, 120, 249));
        fach4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fach4.setText("4");
        fach4.setMaximumSize(new java.awt.Dimension(32000, 32000));
        fach4.setMinimumSize(new java.awt.Dimension(20, 10));
        fach4.setName("fach4"); // NOI18N
        add(fach4);

        fach8.setBackground(new java.awt.Color(252, 159, 72));
        fach8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fach8.setText("8");
        fach8.setMaximumSize(new java.awt.Dimension(32000, 32000));
        fach8.setMinimumSize(new java.awt.Dimension(20, 10));
        fach8.setName("fach8"); // NOI18N
        add(fach8);

        fach1.setBackground(new java.awt.Color(124, 235, 254));
        fach1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fach1.setText("1");
        fach1.setMaximumSize(new java.awt.Dimension(32000, 32000));
        fach1.setMinimumSize(new java.awt.Dimension(20, 10));
        fach1.setName("fach1"); // NOI18N
        add(fach1);

        fach5.setBackground(new java.awt.Color(252, 159, 72));
        fach5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fach5.setText("5");
        fach5.setMaximumSize(new java.awt.Dimension(32000, 32000));
        fach5.setMinimumSize(new java.awt.Dimension(20, 10));
        fach5.setName("fach5"); // NOI18N
        add(fach5);

        fach9.setBackground(new java.awt.Color(250, 27, 27));
        fach9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fach9.setText("9");
        fach9.setMaximumSize(new java.awt.Dimension(32000, 32000));
        fach9.setMinimumSize(new java.awt.Dimension(20, 10));
        fach9.setName("fach9"); // NOI18N
        add(fach9);

        fach2.setBackground(new java.awt.Color(248, 251, 73));
        fach2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fach2.setText("2");
        fach2.setMaximumSize(new java.awt.Dimension(32000, 32000));
        fach2.setMinimumSize(new java.awt.Dimension(20, 10));
        fach2.setName("fach2"); // NOI18N
        add(fach2);

        fach6.setBackground(new java.awt.Color(107, 120, 249));
        fach6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fach6.setText("6");
        fach6.setMaximumSize(new java.awt.Dimension(32000, 32000));
        fach6.setMinimumSize(new java.awt.Dimension(20, 10));
        fach6.setName("fach6"); // NOI18N
        add(fach6);

        fach10.setBackground(new java.awt.Color(252, 159, 72));
        fach10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fach10.setText("10");
        fach10.setMaximumSize(new java.awt.Dimension(32000, 32000));
        fach10.setMinimumSize(new java.awt.Dimension(20, 10));
        fach10.setName("fach10"); // NOI18N
        fach10.setPreferredSize(new java.awt.Dimension(46, 32));
        add(fach10);

        fach3.setBackground(new java.awt.Color(250, 27, 27));
        fach3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fach3.setText("3");
        fach3.setMaximumSize(new java.awt.Dimension(32000, 32000));
        fach3.setMinimumSize(new java.awt.Dimension(20, 10));
        fach3.setName("fach3"); // NOI18N
        add(fach3);

        fach7.setBackground(new java.awt.Color(207, 198, 29));
        fach7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fach7.setText("7");
        fach7.setMaximumSize(new java.awt.Dimension(32000, 32000));
        fach7.setMinimumSize(new java.awt.Dimension(20, 10));
        fach7.setName("fach7"); // NOI18N
        add(fach7);

        fach11.setBackground(new java.awt.Color(124, 235, 254));
        fach11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fach11.setText("11");
        fach11.setMaximumSize(new java.awt.Dimension(32000, 32000));
        fach11.setMinimumSize(new java.awt.Dimension(20, 10));
        fach11.setName("fach11"); // NOI18N
        fach11.setPreferredSize(new java.awt.Dimension(46, 32));
        add(fach11);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup auswahl;
    private javax.swing.JToggleButton fach0;
    private javax.swing.JToggleButton fach1;
    private javax.swing.JToggleButton fach10;
    private javax.swing.JToggleButton fach11;
    private javax.swing.JToggleButton fach2;
    private javax.swing.JToggleButton fach3;
    private javax.swing.JToggleButton fach4;
    private javax.swing.JToggleButton fach5;
    private javax.swing.JToggleButton fach6;
    private javax.swing.JToggleButton fach7;
    private javax.swing.JToggleButton fach8;
    private javax.swing.JToggleButton fach9;
    // End of variables declaration//GEN-END:variables

}
