/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SuchDialog.java
 *
 * Created on 07.09.2011, 12:36:14
 */
package schliessfach.dialoge;

import java.awt.Toolkit;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author fschuett
 */
public class SuchDialog extends javax.swing.JDialog {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String[] liste;
    private String beginn;
    private boolean abgebrochen;

    /** Creates new form SuchDialog */
    public SuchDialog(java.awt.Frame parent, String[] eineListe) {
        super(parent, true);
        abgebrochen = false;
        beginn = "";
        liste = eineListe != null? eineListe : new String[]{};
        initComponents();
        suchListe.setListData(liste);
        ((AbstractDocument) suchen.getDocument()).setDocumentFilter(new DocumentFilter() {

            @Override
            public void replace(FilterBypass fb, int ofs, int len, String s, AttributeSet a) throws BadLocationException {
                beginn = suchen.getText().substring(0, ofs);
                try {
                    int index = Arrays.binarySearch(liste, beginn + s);
                    if (index < 0) {
                        index = -(index + 1);
                    }
                    if (index >= liste.length || !liste[index].startsWith(beginn + s)) {
                        index = -1;
                    }
                    if (index > -1 && index < liste.length) {
                        beginn += s;
                        suchListe.setSelectedValue(liste[index], true);
                        fb.replace(0, suchen.getText().length(), liste[index], a);
                        suchen.getCaret().setDot(liste[index].length());
                        suchen.getCaret().moveDot(beginn.length());
                    } else {
                        Toolkit.getDefaultToolkit().beep();
                    }
                } catch (BadLocationException ex) {
                    Logger.getLogger(SuchDialog.class.getName()).log(Level.SEVERE, null, ex);
                }


            }
        });
        suchen.requestFocusInWindow();
    }

    public void setListe(String[] liste) {
        this.liste = liste;
        suchen.setText("");
        suchListe.setListData(liste);
        beginn = "";
        abgebrochen = false;
    }

    public boolean istAbgebrochen() {
        return abgebrochen;
    }

    public String getResult() {
        return (String) suchListe.getSelectedValue();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        suchen = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        suchListe = new javax.swing.JList();
        schliessen = new javax.swing.JButton();
        gefunden = new javax.swing.JButton();

        setAlwaysOnTop(true);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setName("Suchdialog"); // NOI18N
        setResizable(false);

        suchen.setName("suchen"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        suchListe.setBackground(new java.awt.Color(238, 238, 238));
        suchListe.setFont(new java.awt.Font("Dialog", 0, 12));
        suchListe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        suchListe.setFocusable(false);
        suchListe.setName("suchListe"); // NOI18N
        jScrollPane1.setViewportView(suchListe);

        schliessen.setText("Schließen");
        schliessen.setDefaultCapable(false);
        schliessen.setName("schliessen"); // NOI18N
        schliessen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schliessenActionPerformed(evt);
            }
        });

        gefunden.setText("Gehe Zu");
        gefunden.setName("gefunden"); // NOI18N
        gefunden.setSelected(true);
        gefunden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gefundenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(suchen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(gefunden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(schliessen)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(suchen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schliessen)
                    .addComponent(gefunden))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void schliessenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schliessenActionPerformed
        abgebrochen = true;
        setVisible(false);
    }//GEN-LAST:event_schliessenActionPerformed

    private void gefundenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gefundenActionPerformed
        abgebrochen = false;
        setVisible(false);
    }//GEN-LAST:event_gefundenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                final SuchDialog dialog = new SuchDialog(new javax.swing.JFrame(), null);
                dialog.setListe(new String[]{"Adam", "Eva", "Willibald"});
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        if (dialog.istAbgebrochen()) {
                            System.out.println("Dialog abgebrochen!");
                        } else {
                            System.out.println("Dialog ergabe folgendes Resultat: " + dialog.getResult());
                        }
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gefunden;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton schliessen;
    private javax.swing.JList suchListe;
    private javax.swing.JFormattedTextField suchen;
    // End of variables declaration//GEN-END:variables
}
