/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VertragDlg.java
 *
 * Created on 13.09.2011, 17:38:21
 */

package vertrag;

import historie.Historie;
import historie.Rubrik;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import schliessfach.Schliessfach;
import schliessfach.SchliessfachApp;
import schliessfach.dialoge.SchliessfachAuswahlDlg;

/**
 * 
 * @author fschuett
 */
public class VertragDlg extends javax.swing.JDialog {

	private EntityManager em;
	private Vertrag vertrag;

	/** Creates new form VertragDlg */
	public VertragDlg(java.awt.Frame parent, Vertrag vertrag) {
		super(parent, true);
		em = SchliessfachApp.getApplication().em;
		this.vertrag = vertrag;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jtID = new javax.swing.JFormattedTextField(vertrag.getId());
		jLabel2 = new javax.swing.JLabel();
		jtSchueler = new javax.swing.JFormattedTextField(vertrag.getSchueler());
		jLabel3 = new javax.swing.JLabel();
		jtBeginnJahr = new javax.swing.JFormattedTextField(
				vertrag.getBeginnJahr());
		cbBeginnMitte = new javax.swing.JCheckBox();
		cbBeginnMitte.setSelected(vertrag.isBeginnMitte());
		jLabel4 = new javax.swing.JLabel();
		jtEndeJahr = new javax.swing.JFormattedTextField(vertrag.getEndeJahr());
		cbEndeMitte = new javax.swing.JCheckBox();
		cbEndeMitte.setSelected(vertrag.isEndeMitte());
		jPanel1 = new javax.swing.JPanel();
		fachFreigeben = new javax.swing.JButton();
		fachZuordnen = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tabelleZahlungen = new javax.swing.JTable();
		jbSchliessen = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		schliessfach = new javax.swing.JFormattedTextField(
				vertrag.getSchliessfach());

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Vertrag bearbeiten");

		jLabel1.setText("Vertragsnummer:");
		jLabel1.setName("jLabel1"); // NOI18N

		jtID.setColumns(10);
		jtID.setEditable(false);
		jtID.setName("jtID"); // NOI18N

		jLabel2.setText("Schüler:");
		jLabel2.setName("jLabel2"); // NOI18N

		jtSchueler.setColumns(30);
		jtSchueler.setEditable(false);
		jtSchueler.setName("jtSchueler"); // NOI18N

		jLabel3.setText("Beginn im Schuljahr:");
		jLabel3.setName("jLabel3"); // NOI18N

		jtBeginnJahr.setColumns(10);
		jtBeginnJahr
				.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
						new javax.swing.text.NumberFormatter(
								new java.text.DecimalFormat("#0"))));
		jtBeginnJahr.setName("jtBeginnJahr"); // NOI18N
		jtBeginnJahr
				.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
					public void propertyChange(
							java.beans.PropertyChangeEvent evt) {
						jtBeginnJahrPropertyChange(evt);
					}
				});

		cbBeginnMitte.setText("Beginn Mitte (2. Hj)");
		cbBeginnMitte.setName("cbBeginnMitte"); // NOI18N
		cbBeginnMitte
				.addChangeListener(new javax.swing.event.ChangeListener() {
					public void stateChanged(javax.swing.event.ChangeEvent evt) {
						cbBeginnMitteStateChanged(evt);
					}
				});

		jLabel4.setText("Ende im Schuljahr:");
		jLabel4.setName("jLabel4"); // NOI18N

		jtEndeJahr.setColumns(10);
		jtEndeJahr
				.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
						new javax.swing.text.NumberFormatter(
								new java.text.DecimalFormat("#0"))));
		jtEndeJahr.setName("jtEndeJahr"); // NOI18N
		jtEndeJahr
				.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
					public void propertyChange(
							java.beans.PropertyChangeEvent evt) {
						jtEndeJahrPropertyChange(evt);
					}
				});

		cbEndeMitte.setText("Ende Mitte (1. Hj.)");
		cbEndeMitte.setName("cbEndeMitte"); // NOI18N
		cbEndeMitte.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				cbEndeMitteStateChanged(evt);
			}
		});

		jPanel1.setName("jPanel1"); // NOI18N

		fachFreigeben.setFont(new java.awt.Font("Dialog", 0, 12));
		fachFreigeben.setText("Freigeben");
		fachFreigeben.setName("fachFreigeben"); // NOI18N
		fachFreigeben.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				fachFreigebenActionPerformed(evt);
			}
		});

		fachZuordnen.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
		fachZuordnen.setText("Zuordnen...");
		fachZuordnen.setName("fachZuordnen"); // NOI18N
		fachZuordnen.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				fachZuordnenActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																fachZuordnen,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																fachFreigeben,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																103,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(fachZuordnen)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(fachFreigeben)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jLabel6.setFont(new java.awt.Font("Dialog", 1, 14));
		jLabel6.setText("Zahlungen");
		jLabel6.setEnabled(false);
		jLabel6.setName("jLabel6"); // NOI18N

		jScrollPane1.setName("jScrollPane1"); // NOI18N

		tabelleZahlungen.setModel(vertrag.getZahlungenTableModel());
		tabelleZahlungen.setEnabled(false);
		tabelleZahlungen.setName("tabelleZahlungen"); // NOI18N
		tabelleZahlungen.getTableHeader().setReorderingAllowed(false);
		jScrollPane1.setViewportView(tabelleZahlungen);

		jbSchliessen.setText("Schließen");
		jbSchliessen.setName("jbSchliessen"); // NOI18N
		jbSchliessen.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbSchliessenActionPerformed(evt);
			}
		});

		jLabel5.setText("Schliessfach:");
		jLabel5.setName("jLabel5"); // NOI18N

		schliessfach.setColumns(20);
		schliessfach.setEditable(false);
		schliessfach.setName("schliessfach"); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														586, Short.MAX_VALUE)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel6)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING,
																												false)
																												.addComponent(
																														jLabel5,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														Short.MAX_VALUE)
																												.addComponent(
																														jLabel4,
																														javax.swing.GroupLayout.Alignment.LEADING,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														Short.MAX_VALUE)
																												.addComponent(
																														jLabel3,
																														javax.swing.GroupLayout.Alignment.LEADING,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														Short.MAX_VALUE)
																												.addComponent(
																														jLabel1,
																														javax.swing.GroupLayout.Alignment.LEADING,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														Short.MAX_VALUE)
																												.addComponent(
																														jLabel2,
																														javax.swing.GroupLayout.Alignment.LEADING,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														Short.MAX_VALUE))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING,
																																				false)
																																				.addComponent(
																																						jtEndeJahr)
																																				.addComponent(
																																						jtBeginnJahr))
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(
																																						cbBeginnMitte,
																																						javax.swing.GroupLayout.PREFERRED_SIZE,
																																						194,
																																						javax.swing.GroupLayout.PREFERRED_SIZE)
																																				.addComponent(
																																						cbEndeMitte,
																																						javax.swing.GroupLayout.PREFERRED_SIZE,
																																						183,
																																						javax.swing.GroupLayout.PREFERRED_SIZE)))
																												.addComponent(
																														jtID,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														schliessfach,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														286,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														jtSchueler,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														281,
																														javax.swing.GroupLayout.PREFERRED_SIZE))))
																.addGap(18, 18,
																		18)
																.addComponent(
																		jPanel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(
														jbSchliessen,
														javax.swing.GroupLayout.Alignment.TRAILING))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														jtID,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														jtSchueler,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														jtBeginnJahr,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(cbBeginnMitte))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel4)
																				.addComponent(
																						jtEndeJahr,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						cbEndeMitte))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel5)
																				.addComponent(
																						schliessfach,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(18, 18,
																		18)
																.addComponent(
																		jLabel6))
												.addComponent(
														jPanel1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										308, Short.MAX_VALUE)
								.addGap(18, 18, 18).addComponent(jbSchliessen)
								.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jbSchliessenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbSchliessenActionPerformed
		dispose();
	}// GEN-LAST:event_jbSchliessenActionPerformed

	private void jtBeginnJahrPropertyChange(java.beans.PropertyChangeEvent evt) {// GEN-FIRST:event_jtBeginnJahrPropertyChange
		if ("value".equals(evt.getPropertyName())) {
			Number v = (Number) evt.getNewValue();
			vertrag.setBeginnJahr(v != null ? v.intValue() : null);
		}
	}// GEN-LAST:event_jtBeginnJahrPropertyChange

	private void cbBeginnMitteStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_cbBeginnMitteStateChanged
		vertrag.setBeginnMitte(!vertrag.isBeginnMitte());
	}// GEN-LAST:event_cbBeginnMitteStateChanged

	private void jtEndeJahrPropertyChange(java.beans.PropertyChangeEvent evt) {// GEN-FIRST:event_jtEndeJahrPropertyChange
		if ("value".equals(evt.getPropertyName())) {
			Number v = (Number) evt.getNewValue();
			vertrag.setEndeJahr(v != null ? v.intValue() : null);
		}
	}// GEN-LAST:event_jtEndeJahrPropertyChange

	private void cbEndeMitteStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_cbEndeMitteStateChanged
		vertrag.setEndeMitte(vertrag.isEndeMitte());
	}// GEN-LAST:event_cbEndeMitteStateChanged

	private void fachZuordnenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fachZuordnenActionPerformed
		if (vertrag.getSchliessfach() != null) {
			JOptionPane
					.showMessageDialog(
							this.getParent(),
							"Es it bereits ein Schliessfach zugeordnet.\nGeben Sie dieses zunächst frei.",
							"Schließfach zuordnen", JOptionPane.ERROR_MESSAGE);
			return;
		}
		SchliessfachAuswahlDlg dlg = new SchliessfachAuswahlDlg(SchliessfachApp
				.getApplication().getMainFrame(), vertrag);
		dlg.setLocationRelativeTo(this.getParent());
		dlg.setVisible(true);
		schliessfach.setValue(vertrag.getSchliessfach());
	}// GEN-LAST:event_fachZuordnenActionPerformed

	private void fachFreigebenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fachFreigebenActionPerformed
		if (vertrag.getSchliessfach() == null)
			return;
		Query q = em
				.createQuery("SELECT s FROM Schluessel s WHERE s.schliessfach.nr="
						+ vertrag.getSchliessfach().getNr()
						+ " AND s.ausgegeben=true");
		List l = q.getResultList();
		if (l != null && l.size() > 0) {
			JOptionPane
					.showMessageDialog(
							this.getParent(),
							"Das Schließfach kann nicht freigegeben werden.\nEs ist noch mindestens ein Schlüssel ausgegeben.",
							"Schließfach freigeben", JOptionPane.ERROR_MESSAGE);
			return;
		}
		Schliessfach s = vertrag.getSchliessfach();
		vertrag.setSchliessfach(null);
		em.getTransaction().begin();
		Historie.anhaengen(Rubrik.VERTRAG, vertrag.getSchueler().getNr()
				.toString(), "Schliessfach freigeben: " + s.toString()
				+ " -> null");
		s.setVertrag(null);
		Historie.anhaengen(Rubrik.SCHLIESSFACH, s.getNr().toString(),
				"Vertrag freigeben: " + vertrag.toString() + " -> null");
		em.getTransaction().commit();
		schliessfach.setValue(vertrag.getSchliessfach());
	}// GEN-LAST:event_fachFreigebenActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				VertragDlg dialog = new VertragDlg(new javax.swing.JFrame(),
						new Vertrag());
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JCheckBox cbBeginnMitte;
	private javax.swing.JCheckBox cbEndeMitte;
	private javax.swing.JButton fachFreigeben;
	private javax.swing.JButton fachZuordnen;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton jbSchliessen;
	private javax.swing.JFormattedTextField jtBeginnJahr;
	private javax.swing.JFormattedTextField jtEndeJahr;
	private javax.swing.JFormattedTextField jtID;
	private javax.swing.JFormattedTextField jtSchueler;
	private javax.swing.JFormattedTextField schliessfach;
	private javax.swing.JTable tabelleZahlungen;
	// End of variables declaration//GEN-END:variables

}
