CREATE TABLE "APP"."GEBUEHR"
(
   ID bigint NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY
              (START WITH 1, INCREMENT BY 1),
   ART int,
   ABJAHR int,
   ZEITPUNKT date,
   BETRAG float(52)
)
;
CREATE TABLE "APP"."JAHRE"
(
   ID bigint NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY
              (START WITH 1, INCREMENT BY 1),
   JAHR bigint,
   KOMMENTAR varchar(255)
)
;
CREATE TABLE "APP"."SCHLIESSFACH"
(
   ID bigint NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY
              (START WITH 1, INCREMENT BY 1),
   ORT varchar(255),
   POSITION int,
   SCHRANKID bigint,
   KOMMENTAR varchar(255),
   NR bigint,
   VERTRAG bigint
)
;
CREATE TABLE "APP"."SCHLUESSEL"
(
   ID bigint NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY
              (START WITH 1, INCREMENT BY 1),
   AUSGABE date,
   KOMMENTAR varchar(255),
   AUSGEGEBEN smallint DEFAULT 0,
   NR bigint,
   FACH bigint,
   ANVERTRAG bigint
)
;
CREATE TABLE "APP"."SCHUELER"
(
   ID bigint NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY
              (START WITH 1, INCREMENT BY 1),
   VORNAME varchar(255),
   GEBURT date,
   STATUS int,
   KLASSE varchar(255),
   NR bigint,
   LEHRER varchar(255),
   NACHNAME varchar(255)
)
;
CREATE TABLE "APP"."VERTRAG"
(
   ID bigint NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY
              (START WITH 1, INCREMENT BY 1),
   ENDEJ int,
   ENDES smallint DEFAULT 0,
   BEGINNJ int,
   BEGINNS smallint DEFAULT 0,
   SCHUELER bigint,
   FACH bigint
)
;
CREATE TABLE "APP"."ZAHLUNG"
(
   ID bigint NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY
              (START WITH 1, INCREMENT BY 1),
   KOMMENTAR varchar(255),
   LEIHJAHR int,
   ART int,
   BETRAG float(52),
   ZEITPUNKT date,
   VERTRAG bigint
)
;
CREATE TABLE "APP"."HISTORIE"
(
   ID bigint NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY
              (START WITH 1, INCREMENT BY 1),
   ZEITPUNKT date,
   RUBRIK int,
   KENNUNG varchar(255),
   INHALT varchar(255)
)
;
CREATE TABLE "APP"."KONSTANTEN"
(
   KENNUNG varchar(255) NOT NULL PRIMARY KEY,
   INHALT varchar(255)
)
;
ALTER TABLE "APP"."SCHLIESSFACH"
ADD CONSTRAINT SCHLIESSFACHVRTRAG
FOREIGN KEY (VERTRAG)
REFERENCES "APP"."VERTRAG"(ID)
;
ALTER TABLE "APP"."SCHLUESSEL"
ADD CONSTRAINT SCHLUESSELNVERTRAG
FOREIGN KEY (ANVERTRAG)
REFERENCES "APP"."VERTRAG"(ID)
;
ALTER TABLE "APP"."SCHLUESSEL"
ADD CONSTRAINT FK_SCHLUESSEL_FACH
FOREIGN KEY (FACH)
REFERENCES "APP"."SCHLIESSFACH"(ID)
;
ALTER TABLE "APP"."VERTRAG"
ADD CONSTRAINT VERTRAG_SCHUELER
FOREIGN KEY (SCHUELER)
REFERENCES "APP"."SCHUELER"(ID)
;
ALTER TABLE "APP"."VERTRAG"
ADD CONSTRAINT FK_VERTRAG_FACH
FOREIGN KEY (FACH)
REFERENCES "APP"."SCHLIESSFACH"(ID)
;
ALTER TABLE "APP"."ZAHLUNG"
ADD CONSTRAINT FK_ZAHLUNG_VERTRAG
FOREIGN KEY (VERTRAG)
REFERENCES "APP"."VERTRAG"(ID)
;
INSERT INTO "APP"."KONSTANTEN" VALUES('DBVERSION','2.0')
;
