/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DruckVorschauDlg.java
 *
 * Created on 01.10.2011, 10:28:31
 */
package drucken;

import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.jdesktop.application.Action;

import schliessfach.SchliessfachApp;

/**
 *
 * @author fschuett
 */
public class DruckVorschauDlg extends javax.swing.JDialog {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String kopfText;

    /** Creates new form DruckVorschauDlg */
    public DruckVorschauDlg(java.awt.Frame parent, String inhalt, String kopfText) {
        super(parent, true);
        initComponents();
        this.inhalt.setText(inhalt);
        this.kopfText = kopfText==null? "" : kopfText;
        this.lKopf.setText(kopfText);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        schliesse = new javax.swing.JButton();
        drucke = new javax.swing.JButton();
        einstellen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inhalt = new javax.swing.JEditorPane();
        lKopf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Druckvorschau");
        setModal(true);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(schliessfach.SchliessfachApp.class).getContext().getActionMap(DruckVorschauDlg.class, this);
        schliesse.setAction(actionMap.get("schliessen")); // NOI18N
        schliesse.setName("schliesse"); // NOI18N

        drucke.setAction(actionMap.get("drucken")); // NOI18N
        drucke.setName("drucke"); // NOI18N

        einstellen.setText("Einstellungen...");
        einstellen.setName("einstellen"); // NOI18N
        einstellen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                einstellenActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        inhalt.setContentType("text/html"); // NOI18N
        inhalt.setEditable(false);
        inhalt.setName("inhalt"); // NOI18N
        jScrollPane1.setViewportView(inhalt);

        lKopf.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        lKopf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lKopf.setName("lKopf"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addComponent(lKopf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(einstellen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(drucke)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(schliesse)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lKopf, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schliesse)
                    .addComponent(drucke)
                    .addComponent(einstellen))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void einstellenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_einstellenActionPerformed
        SchliessfachApp app = SchliessfachApp.getApplication();
        DruckerEinstellung dlg = new DruckerEinstellung(app.druckDienst, app.druckAttribut);
        if (dlg.zeigeDialog()) {
            app.druckDienst = dlg.getDruckDienst();
            app.druckAttribut = dlg.getDruckAttribut();
        }
    }//GEN-LAST:event_einstellenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DruckVorschauDlg dialog = new DruckVorschauDlg(new javax.swing.JFrame(), "<html><head><title>Test</title></head><body><h1>Test</h1></body></html>","11a");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Action
    public void schliessen() {
        dispose();
    }

    @Action
    public void drucken() {
        try {
            inhalt.print(new MessageFormat(kopfText), 
                    new MessageFormat(String.format("%1$tc",
                    SchliessfachApp.getApplication().heute.getTime())+" - Seite {0}"),
                    false, SchliessfachApp.getApplication().druckDienst,
                    SchliessfachApp.getApplication().druckAttribut, true);
            dispose();
        } catch (PrinterException ex) {
            Logger.getLogger(DruckVorschauDlg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton drucke;
    private javax.swing.JButton einstellen;
    private javax.swing.JEditorPane inhalt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lKopf;
    private javax.swing.JButton schliesse;
    // End of variables declaration//GEN-END:variables
}
