/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DruckVorschauDlg.java
 *
 * Created on 01.10.2011, 10:28:31
 */
package hilfe;

import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.text.MessageFormat;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.jdesktop.application.Action;

import schliessfach.SchliessfachApp;

/**
 *
 * @author fschuett
 */
public class HilfeDlg extends javax.swing.JDialog {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String kopfText = "Hinweise";
	private String DATEI = "Hilfe"; 
	
	/** Creates new form DruckVorschauDlg */
    public HilfeDlg(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        InputStream htmlF = this.getClass().getResourceAsStream(DATEI + ".html");
        if(htmlF != null) {
        	String inhalt = "";
        	Scanner inF = new Scanner(htmlF);
        	while(inF.hasNextLine())
        		inhalt += inF.nextLine();
        	this.inhalt.setText(inhalt);
        } else {
        this.inhalt.setText(fehlerText(DATEI + ".html"));
        }
        this.lKopf.setText(kopfText);
    }

	private String fehlerText(String dateiname) {
		return "<html><head><title>Hinweise nicht gefunden</title></head>"
        		+ "<body><h1>Hinweise nicht gefunden</h1>"
        		+ "<p>Die Datei mit dem Namen "
        		+ dateiname
        		+ "konnte nicht gefunden oder nicht gelesen werden. Die Hilfe ist"
        		+ " nicht verfügbar.</p></body>"
        		+ "</html";
	}
	
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        schliesse = new javax.swing.JButton();
        drucke = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inhalt = new javax.swing.JEditorPane();
        lKopf = new javax.swing.JLabel();

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(schliessfach.SchliessfachApp.class).getContext().getActionMap(HilfeDlg.class, this);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hinweise");
        setModal(true);

        schliesse.setAction(actionMap.get("schliessen")); // NOI18N
        schliesse.setName("schliesse"); // NOI18N

        drucke.setAction(actionMap.get("drucken")); // NOI18N
        drucke.setName("drucke"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        inhalt.setContentType("text/html"); // NOI18N
        inhalt.setEditable(false);
        inhalt.setName("inhalt"); // NOI18N
        jScrollPane1.setViewportView(inhalt);

        lKopf.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        lKopf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lKopf.setName("lKopf"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addComponent(lKopf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(drucke)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(schliesse)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lKopf, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schliesse)
                    .addComponent(drucke))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                HilfeDlg dialog = new HilfeDlg(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Action
    public void schliessen() {
        dispose();
    }

    @Action
    public void drucken() {
        try {
            inhalt.print(new MessageFormat(kopfText), 
                    new MessageFormat(String.format("%1$tc",
                    SchliessfachApp.getApplication().heute.getTime())+" - Seite {0}"),
                    false, SchliessfachApp.getApplication().druckDienst,
                    SchliessfachApp.getApplication().druckAttribut, true);
            dispose();
        } catch (PrinterException ex) {
            Logger.getLogger(HilfeDlg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton drucke;
    private javax.swing.JEditorPane inhalt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lKopf;
    private javax.swing.JButton schliesse;
    // End of variables declaration//GEN-END:variables
}
