CREATE TABLE "APP"."HISTORIE"
(
   ID bigint NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY
              (START WITH 1, INCREMENT BY 1),
   ZEITPUNKT date,
   RUBRIK int,
   KENNUNG varchar(255),
   INHALT varchar(255)
)
;
CREATE TABLE "APP"."KONSTANTEN"
(
   KENNUNG varchar(255) NOT NULL PRIMARY KEY,
   INHALT varchar(255)
)
;
INSERT INTO "APP"."KONSTANTEN" VALUES('DBVERSION','2.0')
;
