/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SchuelereingabeDlg.java
 *
 * Created on 16.09.2011, 11:56:54
 */

package schueler;

import historie.Historie;
import historie.Rubrik;

import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import schliessfach.SchliessfachApp;

/**
 *
 * @author fschuett
 */
public class SchuelereingabeDlg extends javax.swing.JDialog {

    private EntityManager em;
    /** Creates new form SchuelereingabeDlg */
    public SchuelereingabeDlg(java.awt.Frame parent) {
        super(parent, true);
        this.em = SchliessfachApp.getApplication().em;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        klasseQuery = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT DISTINCT s.klasse FROM Schueler s ORDER BY s.klasse ASC");
        klasseListe = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(klasseQuery.getResultList());
        lehrerQuery = java.beans.Beans.isDesignTime() ? null : em.createQuery("SELECT DISTINCT s.lehrer FROM Schueler s ORDER BY s.lehrer ASC");
        lehrerListe = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : lehrerQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nachName = new javax.swing.JTextField();
        schuelerNr = new javax.swing.JFormattedTextField();
        vorName = new javax.swing.JTextField();
        geburt = new javax.swing.JFormattedTextField();
        klasse = new javax.swing.JComboBox();
        lehrer = new javax.swing.JComboBox();
        abbrechen = new javax.swing.JButton();
        hinzufuegen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Schüler hinzufügen");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Schülerdaten", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText("Schülernummer:");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Nachname:");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Vorname:");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("Geburtsdatum:");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText("Klasse:");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText("Lehrer:");
        jLabel6.setName("jLabel6"); // NOI18N

        nachName.setColumns(20);
        nachName.setName("nachName"); // NOI18N

        schuelerNr.setColumns(7);
        schuelerNr.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        schuelerNr.setName("schuelerNr"); // NOI18N

        vorName.setName("vorName"); // NOI18N

        geburt.setColumns(10);
        geburt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        geburt.setName("geburt"); // NOI18N

        klasse.setName("klasse"); // NOI18N

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, klasseListe, klasse);
        bindingGroup.addBinding(jComboBoxBinding);

        lehrer.setName("lehrer"); // NOI18N

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lehrerListe, lehrer);
        bindingGroup.addBinding(jComboBoxBinding);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nachName)
                    .addComponent(schuelerNr, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vorName)
                    .addComponent(geburt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lehrer, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(klasse, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(schuelerNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nachName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(vorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(geburt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(klasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lehrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        abbrechen.setText("Abbrechen");
        abbrechen.setName("abbrechen"); // NOI18N
        abbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abbrechenActionPerformed(evt);
            }
        });

        hinzufuegen.setText("Hinzufügen");
        hinzufuegen.setName("hinzufuegen"); // NOI18N
        hinzufuegen.setSelected(true);
        hinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hinzufuegenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(hinzufuegen)
                        .addGap(18, 18, 18)
                        .addComponent(abbrechen)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abbrechen)
                    .addComponent(hinzufuegen))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abbrechenActionPerformed
        dispose();
    }//GEN-LAST:event_abbrechenActionPerformed

    private void hinzufuegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hinzufuegenActionPerformed
        try {
            Schueler s = new Schueler(((Number)schuelerNr.getValue()).longValue(), SchuelerStatus.AKTIV, nachName.getText(), vorName.getText(),geburt.getText(),(String)klasse.getSelectedItem(), (String)lehrer.getSelectedItem());
            Query q = em.createQuery(("SELECT s.nr FROM Schueler s WHERE s.nr="+s.getNr()));
            if(!q.getResultList().isEmpty()){
                Schueler alt = (Schueler) q.getSingleResult();
                if(alt.getStatus() == SchuelerStatus.INAKTIV){
                    int result = JOptionPane.showConfirmDialog(this.getParent(), "Ein ehemaliger Schüler mit dieser Nummer existiert.\nSoll dieser Schüler wieder aktiviert werden.", "Schüler hinzufügen", JOptionPane.YES_NO_OPTION);
                    if(result != JOptionPane.YES_OPTION)
                        return;
                }
                else {
                    JOptionPane.showMessageDialog(this.getParent(), "Die Schülernummer ist ungültig.\nEin Schüler mir dieser Nummer existiert bereits.","Schüler hinzufügen",JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            em.getTransaction().begin();
            em.persist(s);
            Historie.anhaengen(Rubrik.SCHUELER, s.getNr().toString(), "hinzugefügt: "+s.toString());
            em.getTransaction().commit();
            JOptionPane.showMessageDialog(this.getParent(), "Der Schüler "+s.getNachName()+","+s.getVorName()+"\nwurde hinzugefügt.", "Schüler hinzufügen", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }
        catch(NumberFormatException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this.getParent(), "Das Schülernummernfeld ist leer oder ungültig.", "Schüler hinzufügen", JOptionPane.ERROR_MESSAGE);
        }
        catch(NullPointerException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this.getParent(), "Eines der erforderlichen Datenfelder ist leer.", "Schüler hinzufügen", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_hinzufuegenActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SchuelereingabeDlg dialog = new SchuelereingabeDlg(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abbrechen;
    private javax.swing.JFormattedTextField geburt;
    private javax.swing.JButton hinzufuegen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox klasse;
    private java.util.List<String> klasseListe;
    private javax.persistence.Query klasseQuery;
    private javax.swing.JComboBox lehrer;
    private java.util.List<String> lehrerListe;
    private javax.persistence.Query lehrerQuery;
    private javax.swing.JTextField nachName;
    private javax.swing.JFormattedTextField schuelerNr;
    private javax.swing.JTextField vorName;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
